export const ADD_COMMENTS = 'ADD_COMMENTS';
export const GET_COMMENTS_PENDING = 'GET_COMMENTS_PENDING';
export const GET_COMMENTS_FULFILLED = 'GET_COMMENTS_FULFILLED';
export const GET_COMMENTS_REJECTED = 'GET_COMMENTS_REJECTED';
export const GET_COMMENTS = 'GET_COMMENTS';
